package com.vates.vsp.asistencia.business;

import com.vates.vsp.alumnos.business.Alumnos;
import com.vates.vsp.alumnos.business.Clases;

// default package
// Generated 06-oct-2010 18:59:18 by Hibernate Tools 3.3.0.GA

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia implements java.io.Serializable {

	private Integer id;
	private Alumnos alumnos;
	private Clases clases;
	private int asistio;

	public Asistencia() {
	}

	public Asistencia(Alumnos alumnos, Clases clases, int asistio) {
		this.alumnos = alumnos;
		this.clases = clases;
		this.asistio = asistio;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	public Clases getClases() {
		return this.clases;
	}

	public void setClases(Clases clases) {
		this.clases = clases;
	}

	public int getAsistio() {
		return this.asistio;
	}

	public void setAsistio(int asistio) {
		this.asistio = asistio;
	}

}
