package com.vates.vsp.alumnos.business;

// default package
// Generated 06-oct-2010 18:59:18 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import com.vates.vsp.asistencia.business.Asistencia;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private Integer id;
	private String apellido;
	private String nombre;
	private String email,telefono;
	private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

	public Alumnos() {
	}

	public Alumnos(String apellido, String nombre) {
		this.apellido = apellido;
		this.nombre = nombre;
	}

	public Alumnos(String apellido, String nombre, Set<Asistencia> asistencias) {
		this.apellido = apellido;
		this.nombre = nombre;
		this.asistencias = asistencias;
	}

	public Alumnos(Integer id, String apellido, String nombre, String email,
			String telefono) {
		super();
		this.id = id;
		this.apellido = apellido;
		this.nombre = nombre;
		this.email = email;
		this.telefono = telefono;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Asistencia> getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set<Asistencia> asistencias) {
		this.asistencias = asistencias;
	}

}
